### ISSUE TITLE
Auto discovery

### ISSUE THREAD

**Issue by asafyish** [mrhooray/swim-js#1]
Hi,

I tried understanding from the original article and from the source code here,
Is there an auto-discovery mechanism in swim, or I must provide an initial host for it ?

**Comment by mrhooray** [comment]
an initial list of hosts has to be provide to swim either through configuration management/service discovery service; and it is not covered by swim protocol or this module

**Comment by asbjornenge** [comment]
@asafyish I just made a small [multicast-dns-peer](https://www.npmjs.com/package/multicast-dns-peer) module for this exact purpose :smile: Works fine!
