### ISSUE TITLE
Not possible to set suspectTimeout on membership?

### ISSUE THREAD

**Issue by tswaters** [mrhooray/swim-js#16]
In ./lin/swim.js suspect timeout is set to `this.suspectTimeout`

https://github.com/mrhooray/swim-js/blob/v0.3.2/lib/swim.js#L39

It doesn't appear possible to set this through options - as best as I can determine `this.suspectTimeout` will always be undefined and fall back to the default of 10.

Should this be `opts.suspectTimeout` ?

**Comment by mrhooray** [comment]
resolved by a503300b72291cef7c5f510b58a37d967c901dc3
