### ISSUE TITLE
Gossip custom events

### ISSUE THREAD

**Issue by asbjornenge** [mrhooray/swim-js#2]
Hi, :heart: the module!

I would like to add support for event gossip on top of this module. Is it feasible? I guess it would require meddling with the internal state. Maybe an entrypoint for custom state structs would be preferred? Would make it lots more extensible :+1: :smile: 

Thoughts? Pointers?

**Comment by mrhooray** [comment]
@asbjornenge sorry for getting to this late 

it is pretty straightforward, the [infrastructure](https://github.com/mrhooray/swim-js/blob/master/lib/disseminator.js) to disseminate generic message is already built
currently it's only for updates but it's just a matter of naming and it supports following message format
```
{
  type: <msg type>
  data: {...}
}
```
rename reference to update in disseminator then expose interface for adding custom message and event listener for incoming custom message 

beware that this is over udp so only suitable for small messages
