### ISSUE TITLE
Alternative to TCP

### ISSUE THREAD

**Issue by danielo515** [mrhooray/swim-js#23]
Hello,

Thanks for this library. I'm using it because it is part of the seneca-mesh implementation, and I have to say that it is impressive how well it works.
However, I'm facing a limitation imposed by the underlying UDP protocol. My hello messages are getting bigger than the allowed MTU, so most of them get dropped, while some others are split into chunks, and some of those chunks are lose. 
I can workaround this problem by splitting my Seneca services a bit more, but sooner or later I'll face this problem again.

Could yo provide an alternative using the TCP protocol ? Or a configuration option to opt-in into a different protocol with better support for larger data-sets ?

I'm on a docker environment, and my services has to go through several network hops which adds headers and that is one of the roots of the problem.

This is to some extend related to senecajs/seneca-mesh#75
I want to mention @rjrodger because I think he should be aware of this.

Thanks in advance.

**Comment by mrhooray** [comment]
This implementation tries to stick to the original paper as much as possible which includes using UDP as the transport. The scalable part of SWIM comes from number of messages in the network does not scale with nodes like traditional heartbeat approach, which doesn't exclude TCP as a viable transport option. However
- The ping, ack, ping-req protocol can be somewhat redundant as TCP comes with certain reliability primitives
- We've seen one TCP based implementation in production, where it can be abused for transmitting state rather that lightweight membership data only. I'd suggest using SWIM for membership and only use lightweight references as metadata. If needed, build separate protocol on top of cluster membership to transfer large amount of data, e.g. databases.
