### ISSUE TITLE
NAT (and Docker) support

### ISSUE THREAD

**Issue by mcollina** [mrhooray/swim-js#4]
It seems this module does not work if the exposed processes are under NAT, as it is the case in Docker.

It seems it relies on the `rinfo` information when replying/assigning ids, rather than the address that is advertised.

Example:
```
Sun, 14 Feb 2016 21:58:43 GMT swim:net 192.168.99.100:7799 received sync message { from: '192.168.99.1:7799',
  data: { meta: null, host: '10.0.48.236:7799', state: 0, incarnation: 0 } }
```

**Comment by mcollina** [comment]
If it's ok for you, I'll have a look in sending a PR to fix this problem cc @rjrodger.

**Comment by mrhooray** [comment]
@mcollina just to understand the scenario under NAT
`rinfo` is the remote address which is the NAT, is this correct?
and host of the messages is from `opts.local.host`, which is probably behind NAT

**Comment by mcollina** [comment]
Let me clarify. This is not due to nat at all: it is related on how UDP packets are relied on by OS. however it manifest itself when nat is in place. Node.js (and swim-js) listen to all ip addresses on a given host by default: which means that the outgoing ip might not be what swim-js set as its own identifier. 

The problem relies on the fact that swim-js replies to the address it receives the message from, rather than the address included in the message. Moreover, the message is discarded if the ip addresses do not match: https://github.com/mrhooray/swim-js/blob/master/lib/membership.js#L89-L92. A PR is coming shortly to address this.

Some logs, with debug output enabled.

```
Mon, 22 Feb 2016 18:46:43 GMT swim:net 192.168.99.100:7799 received buffer { from: '192.168.99.1:7799', length: 57 }
Mon, 22 Feb 2016 18:46:43 GMT swim:net 192.168.99.100:7799 received compound message
Mon, 22 Feb 2016 18:46:43 GMT swim:net 192.168.99.100:7799 received sync message { from: '192.168.99.1:7799',
  data:
   { meta: null,
     host: '192.168.1.185:7799',
     state: 0,
     incarnation: 0 } }
```

on the other end:

```
swim:net 192.168.1.185:7799 +0ms sent buffer { to: '192.168.99.100:7799', length: 57 }

events.js:141
      throw er; // Unhandled 'error' event
      ^
JoinFailedError
    at checkJoin [as _onTimeout] (/Users/matteo/Repositories/baseswim/node_modules/swim/lib/swim.js:156:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

I can provide you a couple of js files to show this issue on top of Docker, or any other systems with 2 ip address.
