### ISSUE TITLE
Add ability to add custom codecs

### ISSUE THREAD

**Issue by ksmithut** [mrhooray/swim-js#7]
Looking at the codec code, it seems like it would be pretty simple to support passing in an object with `encode` and `decode` properties.

A little context, I'm having trouble building msgpack on TravisCI, and it would be awesome if msgpack weren't a direct dependency of this module, and could be included as a separate module so those who want a pure javascript solution can have it.

I realize that this would be a breaking change, so if you're not wanting to go that direction, I understand

**Comment by mrhooray** [comment]
@ksmithut 
have you tried [these options](https://github.com/mrhooray/swim-js/blob/master/.travis.yml#L5-L12) in travis.yml to build msgpack successfully?
do you have problem with farmhash?

it's true that native modules are trickier to build, i may consider remove/replace them

**Comment by ksmithut** [comment]
Apologies for leaving this open for so long. I did end up using those travis options to get it to work. Thank you :)
