### ISSUE TITLE
Unhandled 'error' event from dns.js

### ISSUE THREAD

**Issue by ksmithut** [mrhooray/swim-js#9]
I'm instrumenting several swim nodes with Docker and am running into some issues. I've got 3 nodes connected together. When I scale one of them to 3 nodes, the additional two nodes get discovered and join the rest of the nodes, but when I scale it back down to 1 node I get the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND 82fc0632057d
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

It seems that there is an error event that isn't being listened to and I'm having difficulty finding out where in the code. My guess that it had something to do with the [udpSocket in the net.js module](https://github.com/mrhooray/swim-js/blob/master/lib/net.js#L324) but you have an error handler attached there. Maybe an error handler is missing elsewhere? Or maybe it's missing from the core `dgram` module itself. Either way, it doesn't seem super fault tolerant. I'll try to work up a minimum example to reproduce the behavior.

**Comment by mrhooray** [comment]
reproduce would be very helpful
if you find any unhandled errors, free feel to open a pr

**Comment by ksmithut** [comment]
Turns out it was a misconfiguration on my part with docker, plus a docker bug which has been fixed.
